# Generated by Django 3.1.3 on 2021-02-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=120)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('who_did_post', models.IntegerField(blank=True, null=True)),
                ('likes_number', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('dislikes_number', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
