# Generated by Django 3.1.3 on 2021-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userpost_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='trial',
        ),
        migrations.AddField(
            model_name='userpost',
            name='user_who_posted',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
